// <auto-generated />
using System;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Enterprise.Gpt.Repository;

#nullable disable

namespace Enterprise.Gpt.Repository.Migrations
{
    [DbContext(typeof(AIChatDbContext))]
    [Migration("20260517170000_AddUserModel")]
    partial class AddUserModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Enterprise.Gpt.Entity.AIService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.ToTable("AIService", "Core.Ref");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2a91b5-9e5a-4a0a-a57a-ec70b540bbf0"),
                            DateCreated = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "AzureAIFoundry"
                        });
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Conversation", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationDocument", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocumentPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("ConversationDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<SqlVector<float>>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("ConversationDocumentId");

                    b.ToTable("ConversationDocumentPage", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("createdBy");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsToolEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("modifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Model", "Core.Ref");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c36e22ed-262a-47a1-b2ba-06a38355ae0f"),
                            CreatedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            DateCreated = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A mini version of GPT-5, designed for basic tasks and quick responses.",
                            IsToolEnabled = true,
                            ModifiedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            Name = "gpt-5-mini"
                        },
                        new
                        {
                            Id = new Guid("fd01b615-1e9f-46af-957f-e4eaeff02766"),
                            CreatedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            DateCreated = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A nano version of GPT-5, optimized for lightweight tasks and minimal resource usage.",
                            IsToolEnabled = true,
                            ModifiedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            Name = "gpt-5-nano"
                        },
                        new
                        {
                            Id = new Guid("0b3948f5-70df-4697-a033-ae70971e1796"),
                            CreatedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            DateCreated = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A chat version of GPT-5, optimized for conversational tasks and interactive applications.",
                            IsToolEnabled = true,
                            ModifiedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            Name = "gpt-5-chat"
                        });
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.ToTable("User", "Core");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Enterprise.AI@example.com",
                            FirstName = "Enterprise",
                            LastName = "AI"
                        });
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("createdBy");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("modifiedBy");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModelId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[DateDeactivated] IS NULL");

                    b.ToTable("UserModel", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("createdBy");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("modifiedBy");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("UserId", "Permission")
                        .IsUnique()
                        .HasFilter("[DateDeactivated] IS NULL");

                    b.ToTable("UserPermission", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Conversation", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocument", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.Conversation", "Conversation")
                        .WithMany("Documents")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocumentPage", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.ConversationDocument", "ConversationDocument")
                        .WithMany("Pages")
                        .HasForeignKey("ConversationDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConversationDocument");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Model", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.UserModel", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Model");

                    b.Navigation("ModifiedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.UserPermission", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Conversation", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocument", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
