// <auto-generated />
using System;
using Enterprise.Gpt.Repository;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Enterprise.Gpt.Repository.Migrations
{
    [DbContext(typeof(EnterpriseGptDbContext))]
    [Migration("20260825031549_AddModelIsUserSelectable")]
    partial class AddModelIsUserSelectable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Enterprise.Gpt.Entity.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<long>("ContextTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("ProjectId", "DateDeactivated");

                    b.HasIndex("UserId", "DateDeactivated", "DateCreated")
                        .IsDescending(false, false, true);

                    b.HasIndex("UserId", "DateDeactivated", "IsFavorite", "DateCreated")
                        .IsDescending(false, false, false, true);

                    b.ToTable("Conversation", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "DateDeactivated");

                    b.HasIndex("UserId", "DateDeactivated");

                    b.ToTable("ConversationDocument", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("ConversationDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<SqlVector<float>>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int?>("SourceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("ConversationDocumentId", "Index")
                        .IsUnique()
                        .HasFilter("[DateDeactivated] IS NULL");

                    b.ToTable("ConversationDocumentChunk", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid?>("AssistantMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CachedInputTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContextTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<string>("DeploymentName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("InputPricePerMillionTokens")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("OutputPricePerMillionTokens")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ReasoningTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("ToolInputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("ToolOutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DateCreated"), new[] { "UserId", "ConversationId", "ModelId", "ProviderId", "Kind", "Status", "InputTokens", "OutputTokens", "ToolInputTokens", "ToolOutputTokens", "ContextTokens", "InputPricePerMillionTokens", "OutputPricePerMillionTokens" });

                    b.HasIndex("ProviderId");

                    b.HasIndex("ModelId", "DateCreated");

                    b.HasIndex("UserId", "DateCreated");

                    b.HasIndex("ConversationId", "Kind", "DateCreated");

                    b.ToTable("ConversationUsage", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsageMcpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("ConversationUsageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("McpServerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("McpServerId");

                    b.HasIndex("ConversationUsageId", "McpServerId")
                        .IsUnique();

                    b.ToTable("ConversationUsageMcpServer", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsageToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<string>("CallId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ConversationUsageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<string>("DeploymentName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("Iteration")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid?>("McpServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("SubtreeTotalTokens")
                        .HasColumnType("bigint");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ConversationUsageId", "Sequence");

                    b.HasIndex("Kind", "DateCreated");

                    b.HasIndex("McpServerId", "DateCreated");

                    b.ToTable("ConversationUsageToolCall", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsageTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<long?>("CachedInputTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ConversationUsageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("Iteration")
                        .HasColumnType("int");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReasoningTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportedModelId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ResponseId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("ConversationUsageId", "Iteration")
                        .IsUnique();

                    b.ToTable("ConversationUsageTurn", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.McpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<int>("AuthType")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("createdBy");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("IconKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("modifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Scope")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[DateDeactivated] IS NULL");

                    b.ToTable("McpServer", "Core.Ref");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.MessageFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "MessageId")
                        .IsUnique();

                    b.ToTable("MessageFeedback", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<decimal>("ContextWindowSize")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("createdBy");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("DeploymentName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal?>("InputPricePerMillionTokens")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReasoningEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsToolEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserSelectable")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MaxOutputTokens")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("modifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("OutputPricePerMillionTokens")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ProviderId");

                    b.ToTable("Model", "Core.Ref");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c36e22ed-262a-47a1-b2ba-06a38355ae0f"),
                            ContextWindowSize = 0m,
                            CreatedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            DateCreated = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeploymentName = "rr-gpt-5.6-luna",
                            Description = "OpenAI's GPT-5.6 Luna model.",
                            IsDefault = false,
                            IsReasoningEnabled = false,
                            IsToolEnabled = true,
                            IsUserSelectable = true,
                            MaxOutputTokens = 0m,
                            ModifiedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            Name = "RR GPT 5.6 Luna",
                            ProviderId = new Guid("3f2a91b5-9e5a-4a0a-a57a-ec70b540bbf0")
                        });
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("createdBy");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid?>("McpServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("modifiedBy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("McpServerId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[DateDeactivated] IS NULL");

                    b.ToTable("Permission", "Core");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0b1c2d3-e4f5-4a6b-8c7d-9e0f1a2b3c4d"),
                            CreatedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Full administrative access.",
                            IsDefault = false,
                            ModifiedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            CreatedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Upload documents into a conversation or a project.",
                            IsDefault = true,
                            ModifiedById = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            Name = "Upload File"
                        });
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DateDeactivated");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasFilter("[DateDeactivated] IS NULL");

                    b.ToTable("Project", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ProjectDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "DateDeactivated");

                    b.ToTable("ProjectDocument", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ProjectDocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<SqlVector<float>>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDocumentId", "Index")
                        .IsUnique()
                        .HasFilter("[DateDeactivated] IS NULL");

                    b.ToTable("ProjectDocumentChunk", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.ToTable("Provider", "Core.Ref");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2a91b5-9e5a-4a0a-a57a-ec70b540bbf0"),
                            DateCreated = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "AzureOpenAI"
                        },
                        new
                        {
                            Id = new Guid("b7d4e0c3-5a18-4f92-9c6e-2d31f8a70b45"),
                            DateCreated = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "AzureAIFoundry"
                        },
                        new
                        {
                            Id = new Guid("8c4b1f27-6a3d-4d59-9e21-b0f4a7c6d812"),
                            DateCreated = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "AmazonBedrock"
                        },
                        new
                        {
                            Id = new Guid("6f93ec17-e981-409f-a523-700584f1e7d6"),
                            DateCreated = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Anthropic"
                        });
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.ToTable("User", "Core");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f7ab694-1b6c-4b19-badd-c82b65e794cf"),
                            DateCreated = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateModified = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Enterprise.AI@example.com",
                            FirstName = "Enterprise",
                            LastName = "AI"
                        });
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("createdBy");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateCreated");

                    b.Property<DateTimeOffset?>("DateDeactivated")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateDeactivated");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("datetimeoffset")
                        .HasJsonPropertyName("dateModified");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("modifiedBy");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique()
                        .HasFilter("[DateDeactivated] IS NULL");

                    b.ToTable("UserPermission", "Core");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Conversation", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Enterprise.Gpt.Entity.Project", "Project")
                        .WithMany("Conversations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocument", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.Conversation", "Conversation")
                        .WithMany("Documents")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocumentChunk", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.ConversationDocument", "ConversationDocument")
                        .WithMany("Chunks")
                        .HasForeignKey("ConversationDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConversationDocument");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsage", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.Conversation", "Conversation")
                        .WithMany("Usage")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Model");

                    b.Navigation("Provider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsageMcpServer", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.ConversationUsage", "ConversationUsage")
                        .WithMany("McpServers")
                        .HasForeignKey("ConversationUsageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.McpServer", "McpServer")
                        .WithMany()
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConversationUsage");

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsageToolCall", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.ConversationUsage", "ConversationUsage")
                        .WithMany("ToolCalls")
                        .HasForeignKey("ConversationUsageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.McpServer", "McpServer")
                        .WithMany()
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Enterprise.Gpt.Entity.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Enterprise.Gpt.Entity.ConversationUsageToolCall", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ConversationUsage");

                    b.Navigation("McpServer");

                    b.Navigation("Model");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsageTurn", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.ConversationUsage", "ConversationUsage")
                        .WithMany("Turns")
                        .HasForeignKey("ConversationUsageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConversationUsage");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.McpServer", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.MessageFeedback", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Model", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Permission", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.McpServer", "McpServer")
                        .WithMany("Permissions")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Enterprise.Gpt.Entity.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("McpServer");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Project", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ProjectDocument", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ProjectDocumentChunk", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.ProjectDocument", "ProjectDocument")
                        .WithMany("Chunks")
                        .HasForeignKey("ProjectDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectDocument");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.UserPermission", b =>
                {
                    b.HasOne("Enterprise.Gpt.Entity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise.Gpt.Entity.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Conversation", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Usage");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsage", b =>
                {
                    b.Navigation("McpServers");

                    b.Navigation("ToolCalls");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ConversationUsageToolCall", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.McpServer", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.Project", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.ProjectDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Enterprise.Gpt.Entity.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
